package dynamictableapp.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 13:35:45 IST 2014
// ---------------------------------------------------------------------
public interface DynamicTabAM extends ApplicationModule {
    void createNewViewObject(String query);
}

