package dynamictableapp.model.service;

import dynamictableapp.model.service.common.DynamicTabAM;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 13:28:09 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DynamicTabAMImpl extends ApplicationModuleImpl implements DynamicTabAM {
    /**
     * This is the default constructor (do not remove).
     */
    public DynamicTabAMImpl() {
    }

    /**
     * Container's getter for dynamic1.
     * @return dynamic1
     */
    public ViewObjectImpl getdynamic1() {
        return (ViewObjectImpl) findViewObject("dynamic1");
    }

    /**Method to create viewObject using SQL query
     * @param query
     */
    public void createNewViewObject(String query) {
        ViewObject dynVo = this.getdynamic1();
        dynVo.remove();
        this.createViewObjectFromQueryStmt("dynamic1", query);
        this.getdynamic1().executeQuery();
    }

    /**
     * Container's getter for ListOfTablesVO1.
     * @return ListOfTablesVO1
     */
    public ViewObjectImpl getListOfTablesVO() {
        return (ViewObjectImpl) findViewObject("ListOfTablesVO");
    }
}

